/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData stroke_width = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collapse = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData options = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leave_room = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enter_room = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drawing = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eraser = IconData(0xf12d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
